default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: xxxxx #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Overtime_dev
  usernsme: postgres
  password: 'omnipod'

test:
  <<: *default
  database: Overtime_test
  usernsme: postgres
  password: 'omnipod'
  
production:
  <<: *default
  database: project_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
